### ISSUE TITLE
Verification of Information Retrieval from API (stakerslist)

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/astar-token-api#162]
I am using ‘https://api.astar.network/’ to verify information. 
Among them, I am using stakerlist (https://api.astar.network/api/v3/astar/dapps-staking/stakerslist/) to calculate the total amount staked in each dApp. However, it seems that this value has not changed since August 19, 2024. Is the original information that the API, such as the indexer, is providing being updated?

**Comment by bobo-k2** [comment]
Hi @tksarah, please check again. There was an issue with the indexer

**Comment by tksarah** [comment]
Thank you @bobo-k2 

Yes, I have confirmed that it is fixed.
